/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import User.User;
import Repository.KursiRepository;
import Repository.PemesananRepository;
import javax.swing.JOptionPane;
import javax.swing.JButton;

import java.util.ArrayList;
import java.awt.Color;
import Model.Jadwal;

import Repository.JadwalRepository;

import Model.Kursi;
import Model.Pemesanan;

import Repository.KursiRepository;
import Repository.PemesananRepository;

/**
 *
 * @author user
 */
public class PilihKursiForm extends javax.swing.JFrame {
    
    private User userLogin;

    private int idJadwal;

    private int idKursiTerpilih = 0;

    private String nomorKursiTerpilih = "";

    /**
     * Creates new form PilihKursiForm
     */
    public PilihKursiForm( User userLogin,
        int idJadwal) {
        initComponents();
        
        this.userLogin = userLogin;

        this.idJadwal = idJadwal;
        
        loadJadwal();

        loadKursi();
        
    }
    
    private void loadJadwal() {

    JadwalRepository repo =
            new JadwalRepository();

    ArrayList<Jadwal> list =
            repo.getAllJadwal();

        for (Jadwal j : list) {

            if (j.getIdJadwal() == idJadwal) {

                lblKereta.setText(
                        j.getNamaKereta()
                );

                lblRute.setText(
                        j.getAsal()
                        + " - "
                        + j.getTujuan()
                );

                break;
            }
        }
    }
    
    private JButton getButtonByNomor(
        String nomor
    ) {

        switch (nomor) {

            // A
            case "A1": return btnA1;
            case "A2": return btnA2;
            case "A3": return btnA3;
            case "A4": return btnA4;
            case "A5": return btnA5;

            // B
            case "B1": return btnB1;
            case "B2": return btnB2;
            case "B3": return btnB3;
            case "B4": return btnB4;
            case "B5": return btnB5;

            // C
            case "C1": return btnC1;
            case "C2": return btnC2;
            case "C3": return btnC3;
            case "C4": return btnC4;
            case "C5": return btnC5;

            // D
            case "D1": return btnD1;
            case "D2": return btnD2;
            case "D3": return btnD3;
            case "D4": return btnD4;
            case "D5": return btnD5;

            // E
            case "E1": return btnE1;
            case "E2": return btnE2;
            case "E3": return btnE3;
            case "E4": return btnE4;
            case "E5": return btnE5;

            // F
            case "F1": return btnF1;
            case "F2": return btnF2;
            case "F3": return btnF3;
            case "F4": return btnF4;
            case "F5": return btnF5;

            // G
            case "G1": return btnG1;
            case "G2": return btnG2;
            case "G3": return btnG3;
            case "G4": return btnG4;
            case "G5": return btnG5;

            // H
            case "H1": return btnH1;
            case "H2": return btnH2;
            case "H3": return btnH3;
            case "H4": return btnH4;
            case "H5": return btnH5;

            default:
                return null;
        }
}
    
    private void loadKursi() {

    KursiRepository repo =
            new KursiRepository();

    ArrayList<Kursi> list =
            repo.getKursiByJadwal(
                    idJadwal
            );

    for (Kursi k : list) {

        JButton btn =
                getButtonByNomor(
                        k.getNomorKursi()
                );

        if (btn == null) {
            continue;
        }

        if (k.getStatus().equals("Dipesan")) {

            btn.setBackground(Color.RED);

            btn.setOpaque(true);

            btn.setContentAreaFilled(true);

            btn.setEnabled(false);
        } else {

            btn.setBackground(Color.GREEN);

            btn.setOpaque(true);

            btn.setContentAreaFilled(true);

        }
    }
}
    
    private void pilihKursi(String nomor) {

        nomorKursiTerpilih = nomor;

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : " + nomor
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblKereta = new javax.swing.JLabel();
        lblRute = new javax.swing.JLabel();
        btnA1 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Kursi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kereta");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Rute");

        jLabel4.setText(":");

        jLabel5.setText(":");

        lblKereta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKereta.setText("Argo Bromo");

        lblRute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRute.setText("Surabaya - Jakarta ");

        btnA1.setText("A1");
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        btnA2.setText("A2");
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });

        btnA3.setText("A3");
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });

        btnA4.setText("A4");
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });

        btnC4.setText("C4");
        btnC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC4ActionPerformed(evt);
            }
        });

        btnB1.setText("B1");
        btnB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1ActionPerformed(evt);
            }
        });

        btnB2.setText("B2");
        btnB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2ActionPerformed(evt);
            }
        });

        btnC1.setText("C1");
        btnC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC1ActionPerformed(evt);
            }
        });

        btnC2.setText("C2");
        btnC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC2ActionPerformed(evt);
            }
        });

        btnD2.setText("D2");
        btnD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD2ActionPerformed(evt);
            }
        });

        btnE2.setText("E2");
        btnE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE2ActionPerformed(evt);
            }
        });

        btnF2.setText("F2");
        btnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF2ActionPerformed(evt);
            }
        });

        btnG2.setText("G2");
        btnG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2ActionPerformed(evt);
            }
        });

        btnH2.setText("H2");
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });

        btnD1.setText("D1");
        btnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD1ActionPerformed(evt);
            }
        });

        btnE1.setText("E1");
        btnE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE1ActionPerformed(evt);
            }
        });

        btnF1.setText("F1");
        btnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF1ActionPerformed(evt);
            }
        });

        btnG1.setText("G1");
        btnG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1ActionPerformed(evt);
            }
        });

        btnH1.setText("H1");
        btnH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH1ActionPerformed(evt);
            }
        });

        btnB3.setText("B3");
        btnB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB3ActionPerformed(evt);
            }
        });

        btnC3.setText("C3");
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });

        btnD3.setText("D3");
        btnD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD3ActionPerformed(evt);
            }
        });

        btnE3.setText("E3");
        btnE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE3ActionPerformed(evt);
            }
        });

        btnF3.setText("F3");
        btnF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF3ActionPerformed(evt);
            }
        });

        btnG3.setText("G3");
        btnG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG3ActionPerformed(evt);
            }
        });

        btnH3.setText("H3");
        btnH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH3ActionPerformed(evt);
            }
        });

        btnE4.setText("E4");
        btnE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE4ActionPerformed(evt);
            }
        });

        btnD4.setText("D4");
        btnD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD4ActionPerformed(evt);
            }
        });

        btnB4.setText("B4");
        btnB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB4ActionPerformed(evt);
            }
        });

        btnF4.setText("F4");
        btnF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF4ActionPerformed(evt);
            }
        });

        btnG4.setText("G4");
        btnG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG4ActionPerformed(evt);
            }
        });

        btnH4.setText("H4");
        btnH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH4ActionPerformed(evt);
            }
        });

        btnA5.setText("A5");
        btnA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5ActionPerformed(evt);
            }
        });

        btnB5.setText("B5");
        btnB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB5ActionPerformed(evt);
            }
        });

        btnC5.setText("C5");
        btnC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC5ActionPerformed(evt);
            }
        });

        btnD5.setText("D5");
        btnD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD5ActionPerformed(evt);
            }
        });

        btnE5.setText("E5");
        btnE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE5ActionPerformed(evt);
            }
        });

        btnF5.setText("F5");
        btnF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF5ActionPerformed(evt);
            }
        });

        btnG5.setText("G5");
        btnG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG5ActionPerformed(evt);
            }
        });

        btnH5.setText("H5");
        btnH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH5ActionPerformed(evt);
            }
        });

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRute, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnA1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnB1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnC1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnA2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnG2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnF2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnB2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnD2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnC2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnE2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnG3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnF3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnE3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnD3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnC3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnB3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnA3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnH3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnG4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnF4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnA4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnD4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnC4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnE4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnH4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnA5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnB5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnC5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnD5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnE5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnF5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnG5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnH5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(lblKereta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lblRute))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA1)
                    .addComponent(btnA2)
                    .addComponent(btnA3)
                    .addComponent(btnA4)
                    .addComponent(btnA5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnB1)
                    .addComponent(btnB2)
                    .addComponent(btnB3)
                    .addComponent(btnB4)
                    .addComponent(btnB5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC1)
                    .addComponent(btnC2)
                    .addComponent(btnC3)
                    .addComponent(btnC4)
                    .addComponent(btnC5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnD2)
                    .addComponent(btnD1)
                    .addComponent(btnD3)
                    .addComponent(btnD4)
                    .addComponent(btnD5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnE2)
                    .addComponent(btnE1)
                    .addComponent(btnE3)
                    .addComponent(btnE4)
                    .addComponent(btnE5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF2)
                    .addComponent(btnF1)
                    .addComponent(btnF3)
                    .addComponent(btnF4)
                    .addComponent(btnF5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnG2)
                    .addComponent(btnG1)
                    .addComponent(btnG3)
                    .addComponent(btnG4)
                    .addComponent(btnG5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnH2)
                    .addComponent(btnH1)
                    .addComponent(btnH3)
                    .addComponent(btnH4)
                    .addComponent(btnH5))
                .addGap(41, 41, 41)
                .addComponent(btnPesan)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        if (nomorKursiTerpilih.equals("")) {

        JOptionPane.showMessageDialog(
                null,
                "Pilih kursi terlebih dahulu!"
        );

            return;
        }

        KursiRepository kursiRepo =
                new KursiRepository();

        Kursi kursi =
                kursiRepo.getKursiByNomor(
                        idJadwal,
                        nomorKursiTerpilih
                );

        if (kursi == null) {

            JOptionPane.showMessageDialog(
                    null,
                    "Kursi tidak ditemukan!"
            );

            return;
        }

        String kodeBooking =
                "BK"
                + System.currentTimeMillis();

        Pemesanan pemesanan =
                new Pemesanan(
                        0,
                        userLogin.getIdUser(),
                        idJadwal,
                        kursi.getIdKursi(),
                        kodeBooking,
                        "Pending",
                        ""
                );

        PemesananRepository repo =
                new PemesananRepository();

        boolean sukses =
                repo.tambahPemesanan(
                        pemesanan
                );

        if (sukses) {

            kursiRepo.updateStatus(
                    kursi.getIdKursi(),
                    "Dipesan"
            );

            JOptionPane.showMessageDialog(
                    null,
                    "Booking berhasil!\nKode: "
                    + kodeBooking
            );
            
            Pembayaran pembayaran =
            new Pembayaran(
                kodeBooking,
                nomorKursiTerpilih,
                350000
            );

pembayaran.setVisible(true);

dispose();
            
            JButton btn =
                    getButtonByNomor(
                            nomorKursiTerpilih
                    );

            btn.setBackground(
                    Color.RED
            );

            btn.setEnabled(
                false
            );

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Booking gagal!"
            );
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnE5ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnA5ActionPerformed

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnB3ActionPerformed

    private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnB4ActionPerformed

    private void btnB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnB5ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnC4ActionPerformed

    private void btnC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnC5ActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnD2ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnD3ActionPerformed

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnD5ActionPerformed

    private void btnE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnE1ActionPerformed

    private void btnE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnE2ActionPerformed

    private void btnE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnE3ActionPerformed

    private void btnE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnE4ActionPerformed

    private void btnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnF1ActionPerformed

    private void btnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnF2ActionPerformed

    private void btnF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnF3ActionPerformed

    private void btnF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnF4ActionPerformed

    private void btnF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnF5ActionPerformed

    private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnG1ActionPerformed

    private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnG2ActionPerformed

    private void btnG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnG3ActionPerformed

    private void btnG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnG4ActionPerformed

    private void btnG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnG5ActionPerformed

    private void btnH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnH1ActionPerformed

    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnH2ActionPerformed

    private void btnH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnH3ActionPerformed

    private void btnH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnH4ActionPerformed

    private void btnH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JButton btn =
            (javax.swing.JButton) evt.getSource();

        nomorKursiTerpilih =
                btn.getText();

        JOptionPane.showMessageDialog(
                null,
                "Kursi dipilih : "
                + nomorKursiTerpilih
        );
    }//GEN-LAST:event_btnH5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihKursiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihKursiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihKursiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihKursiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnB5;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnC5;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD5;
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnE3;
    private javax.swing.JButton btnE4;
    private javax.swing.JButton btnE5;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnF2;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnG4;
    private javax.swing.JButton btnG5;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnH3;
    private javax.swing.JButton btnH4;
    private javax.swing.JButton btnH5;
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblKereta;
    private javax.swing.JLabel lblRute;
    // End of variables declaration//GEN-END:variables
}
